version: '3'
services:
  web:
    image: node:alpine
    working_dir: /usr/app
    command: npm run dev
    ports:
      - '3000:3000'
    volumes:
      - .:/usr/app
    networks:
      - code-network
  socket:
    image: node:alpine
    working_dir: /usr/app
    command: node socket/index.js
    ports:
      - '5000:5000'
    volumes:
      - .:/usr/app
    networks:
      - code-network

networks:
  code-network:
    driver: bridge
